_format_version: "1.1"

services:
    -   name: v1-auth-auth
        url: http://f1monkey-auth:8080/v1/auth
        routes:
            -   name: auth
                paths:
                    - /v1/auth
        plugins:
            -   name: cors
                config:
                    methods: [HEAD, GET, POST, PUT, DELETE, OPTIONS]
                    headers: ['Accept', 'Content-Length', 'Content-Type', 'Authorization', 'X-Debug']
                    credentials: true
                    origins: ['*']
    -   name: v1-auth-sessions
        url: http://f1monkey-auth:8080/v1/sessions
        routes:
            -   name: sessions
                paths:
                    - /v1/sessions
        plugins:
            -   name: cors
                config:
                    methods: [HEAD, GET, POST, PUT, DELETE, OPTIONS]
                    headers: ['Accept', 'Content-Length', 'Content-Type', 'Authorization', 'X-Debug']
                    credentials: true
                    origins: ['*']
    -   name: v1-eve-characters-access-tokens
        url: http://f1monkey-eve-characters:8080/v1/access-tokens
        routes:
            -   name: access-tokens
                paths:
                    - /v1/access-tokens
        plugins:
            -   name: cors
                config:
                    methods: [HEAD, GET, POST, PUT, DELETE, OPTIONS]
                    headers: ['Accept', 'Content-Length', 'Content-Type', 'Authorization', 'X-Debug']
                    credentials: true
                    origins: ['*']
    -   name: v1-eve-characters-characters
        url: http://f1monkey-eve-characters:8080/v1/characters
        routes:
            -   name: characters
                paths:
                    - /v1/characters
        plugins:
            -   name: cors
                config:
                    methods: [HEAD, GET, POST, PUT, DELETE, OPTIONS]
                    headers: ['Accept', 'Content-Length', 'Content-Type', 'Authorization', 'X-Debug']
                    credentials: true
                    origins: ['*']
    -   name: v1-eve-characters-market
        url: http://f1monkey-eve-market:8080/v1
        routes:
            -   name: market
                paths:
                    - /v1/market
        plugins:
            -   name: cors
                config:
                    methods: [HEAD, GET, POST, PUT, DELETE, OPTIONS]
                    headers: ['Accept', 'Content-Length', 'Content-Type', 'Authorization', 'X-Debug']
                    credentials: true
                    origins: ['*']
